name: Build

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14, 16]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }} @ ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: |
        npm ci
        npm i -g rimraf

    - name: Build production assets
      run: npm run build
